[package]
name = "unum_o3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "*"
duplicate = "*"
num-traits = "*"
rug = "*"
 
bitvec = "*"
gmp-mpfr-sys = {version = "~1.5"}
rig = "*"
